on:
  workflow_call:
    inputs:
      needs-push:
        required: true
        type: boolean
    outputs:
      tag:
        value: ${{ jobs.build.outputs.tag }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: buildx
        name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/arthur1/mackerel-sesame
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: build image
        uses: docker/build-push-action@v4
        with:
          push: ${{ inputs.needs-push }}
          context: .
          file: ./docker/mackerel-sesame/Dockerfile
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: get one of tags
        id: tag
        run: |
          echo "tag=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT"
