on:
  workflow_call:
    inputs:
      new-image-tag:
        required: true
        type: string

jobs:
  dispatch-for-iot-monitor-mackerel-sesame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 364898
          private-key: ${{ secrets.ARTHUR1_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: home-k8s
      - uses: Arthur1/home-k8s/actions/dispatch-bump-image-version@main
        with:
          image-name: ghcr.io/arthur1/mackerel-sesame
          new-image-tag: ${{ inputs.new-image-tag }}
          target-file: manifests/iot-monitor/mackerel-sesame/cronjob.yml
          token: ${{ steps.app-token.outputs.token }}
